language: node_js

node_js:
  - 10
  - 8
  - 6

env:
  - TYPESCRIPT_VERSION="3.1"
  - TYPESCRIPT_VERSION="3.0"
  - TYPESCRIPT_VERSION="2.9"
  - TYPESCRIPT_VERSION="2.8"
  - TYPESCRIPT_VERSION="2.7"
  - TYPESCRIPT_VERSION="2.6"
  - TYPESCRIPT_VERSION="2.5"
  - TYPESCRIPT_VERSION="2.4"
  - TYPESCRIPT_VERSION="2.3"
  - TYPESCRIPT_VERSION="2.2"
  - TYPESCRIPT_VERSION="2.1"

script:
  - yarn lint
  - yarn add typescript@${TYPESCRIPT_VERSION}
  - yarn ci
